using Suity.Editor.Types;
using Suity.Editor.Values;
using System.Collections.Generic;
using System.Drawing;
using System.Threading.Tasks;

namespace Suity.Editor.AIGC.Assistants;

/// <summary>
/// Abstract service for handling AI-driven generative operations on node graphs and data structures.
/// </summary>
public abstract class AIGenerativeService
{
    internal static AIGenerativeService _external;

    /// <summary>
    /// Gets the singleton instance of the generative service.
    /// </summary>
    public static AIGenerativeService Instance => _external;

    /// <summary>
    /// Creates a node graph design based on the generative request.
    /// </summary>
    /// <param name="request">The generative request context.</param>
    /// <param name="intent">The intent of the generation (create or edit).</param>
    /// <returns>The resulting node graph design.</returns>
    public abstract Task<FlowGraphDesignResult> HandleCreateNodeGraph(AIGenerativeRequest request, GenerativeIntent intent);

    /// <summary>
    /// Creates a node graph design based on the node graph design request.
    /// </summary>
    /// <param name="request">The node graph design request.</param>
    /// <param name="intent">The intent of the generation (create or edit).</param>
    /// <returns>The resulting node graph design.</returns>
    public abstract Task<FlowGraphDesignResult> HandleCreateNodeGraph(AINodeGraphDesignRequest request, GenerativeIntent intent);

    /// <summary>
    /// Builds a context string describing the given types for use in AI prompts.
    /// </summary>
    /// <param name="types">The list of compound function call types.</param>
    /// <param name="noticeTargetType">Whether to include target type notices.</param>
    /// <returns>A context string describing the types.</returns>
    public abstract string BuildTypeContext(List<DCompondFunctionCallType> types, bool noticeTargetType);

    /// <summary>
    /// Gets the full JSON representation of an SObject, including all fields.
    /// </summary>
    /// <param name="sobj">The SObject to serialize.</param>
    /// <param name="excludedFields">Optional fields to exclude from the output.</param>
    /// <returns>A JSON string representation of the object.</returns>
    public abstract string GetFieldJson(SObject sobj, ICollection<DStructField> excludedFields = null);

    /// <summary>
    /// Get json without complex fields
    /// </summary>
    /// <param name="sobj">The SObject to serialize.</param>
    /// <param name="excludedFields">Optional fields to exclude from the output.</param>
    /// <returns>A JSON string with only simple fields.</returns>
    public abstract string GetSimpleFieldJson(SObject sobj, ICollection<DStructField> excludedFields = null);
}


#region Node graph design info

/// <summary>
/// Represents the complete design result of a node graph generated by AI.
/// </summary>
public class FlowGraphDesignResult
{
    /// <summary>
    /// Gets or sets the ID of the first (root) node in the graph.
    /// </summary>
    public string FirstNodeId { get; set; }

    /// <summary>
    /// Gets or sets the dictionary of all nodes keyed by their IDs.
    /// </summary>
    public Dictionary<string, FlowNodeDesignResult> Nodes { get; set; }
    
    /// <summary>
    /// Gets or sets the list of links created during generation.
    /// </summary>
    public List<FlowLinkDesignResult> CreatedLinks { get; set; }

    /// <summary>
    /// Gets or sets the list of links removed during generation.
    /// </summary>
    public List<FlowLinkDesignResult> RemovedLinks { get; set; }
}

/// <summary>
/// Represents the design result of a single node in a node graph.
/// </summary>
public class FlowNodeDesignResult
{
    /// <summary>
    /// Gets or sets the unique identifier of the node.
    /// </summary>
    public string NodeId { get; set; }

    /// <summary>
    /// Gets or sets the description of what this node should do.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Gets or sets the type definition for this node.
    /// </summary>
    public DCompondFunctionCallType NodeType { get; set; }

    /// <summary>
    /// Gets or sets the generated data object for this node.
    /// </summary>
    public SObject NodeData { get; set; }

    /// <summary>
    /// Gets or sets the position of the node in the graph editor.
    /// </summary>
    public Point Position { get; set; }

    public override string ToString()
    {
        string typeId = NodeType?.Type?.FullTypeName;

        return $"<node id='{NodeId}' type='{typeId}'>\n{Description}\n</node>";

        //return NodeId ?? string.Empty;
    }
}

/// <summary>
/// Represents a link (connection) between two nodes in a node graph design.
/// </summary>
public class FlowLinkDesignResult
{
    /// <summary>
    /// Gets or sets the ID of the source node.
    /// </summary>
    public string FromNodeId { get; set; }

    /// <summary>
    /// Gets or sets the field on the source node used for the connection.
    /// </summary>
    public DStructField Field { get; set; }

    /// <summary>
    /// Gets or sets the ID of the target node.
    /// </summary>
    public string ToNodeId { get; set; }

    public override string ToString()
    {
        return $"{FromNodeId}.{Field.Name} -> {ToNodeId}";
    }
}

#endregion