using Suity.Editor.Design;
using Suity.Editor.Values;
using Suity.Synchonizing;
using Suity.Views;
using System;
using System.Drawing;
using static Suity.Helpers.GlobalLocalizer;

namespace Suity.Editor.Types;

/// <summary>
/// Provides a design-time representation of a field type, supporting type selection, array toggling, and synchronization.
/// </summary>
[NativeAlias]
public class FieldTypeDesign : ITypeDesign, ISyncObject, IViewObject, INavigable
{
    private readonly object _owner;

    // This value indicates whether this type design can be left unfilled, not whether the field generated by this type can be left unfilled.
    private readonly bool _optional;

    private TypeDesignSelection _baseType = new();
    private bool _isArray;

    private string _lateTypeString;

    /// <summary>
    /// Event raised when the field type changes.
    /// </summary>
    public event EventHandler FieldTypeChanged;

    /// <summary>
    /// Creates a new instance of <see cref="FieldTypeDesign"/>.
    /// </summary>
    /// <param name="owner">The owner object that contains this field type design.</param>
    public FieldTypeDesign(object owner)
    {
        _owner = owner;
    }

    /// <summary>
    /// Creates a new instance of <see cref="FieldTypeDesign"/> with optional flag.
    /// </summary>
    /// <param name="owner">The owner object that contains this field type design.</param>
    /// <param name="optional">Whether this type design can be left unfilled.</param>
    public FieldTypeDesign(object owner, bool optional)
        : this(owner)
    {
        _baseType.Optional = _optional = optional;
    }

    /// <summary>
    /// Gets or sets the complete type definition
    /// </summary>
    public TypeDefinition FieldType
    {
        get
        {
            Guid id = BaseType.Id;
            if (id == Guid.Empty)
            {
                // If type string is set, try to resolve
                if (!string.IsNullOrWhiteSpace(_lateTypeString))
                {
                    // Try to resolve the cached type string
                    var resolvedType = ResolveLateType();
                    if (!TypeDefinition.IsNullOrEmpty(resolvedType))
                    {
                        // Successfully resolved, set type definition
                        SetFieldType(resolvedType);
                    }
                    else
                    {
                        // Resolution failed, return empty
                        return TypeDefinition.Empty;
                    }
                }
                else
                {
                    // No type definition, return empty
                    return TypeDefinition.Empty;
                }
            }

            TypeDefinition typeInfo = TypeDefinition.Resolve(BaseType.Prefix + id);
            if (IsArray)
            {
                typeInfo = typeInfo.MakeArrayType();
            }

            return typeInfo;
        }
        set
        {
            SetFieldType(value);

            FieldTypeChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    /// <summary>
    /// Gets or sets the type string representation. Resolves the type from the string if possible.
    /// </summary>
    public string TypeString
    {
        get
        {
            var type = FieldType;
            if (type != TypeDefinition.Empty)
            {
                return type.TypeCode;
            }
            else
            {
                return _lateTypeString ?? string.Empty;
            }
        }
        set
        {
            _lateTypeString = value;

            var type = ResolveLateType();

            if (!TypeDefinition.IsNullOrEmpty(type))
            {
                SetFieldType(type);
            }
            else
            {
                SetFieldType(TypeDefinition.Empty);
            }

            FieldTypeChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    /// <summary>
    /// Gets or sets the type without array definition
    /// </summary>
    public TypeDesignSelection BaseType
    {
        get => _baseType;
        set
        {
            value ??= new TypeDesignSelection();
            if (_baseType.Equals(value))
            {
                return;
            }

            _baseType = value;
            _baseType.Optional = _optional;

            FieldTypeChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    /// <summary>
    /// Gets or sets whether the type is an array.
    /// </summary>
    public bool IsArray
    {
        get => _isArray;
        set
        {
            if (_isArray == value)
            {
                return;
            }

            _isArray = value;
            FieldTypeChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    /// <summary>
    /// Gets the display text for the current field type.
    /// </summary>
    public string DisplayText
    {
        get
        {
            var fieldType = FieldType;

            if (!TypeDefinition.IsNullOrEmpty(fieldType))
            {
                return fieldType.ToDisplayString();
            }
            
            if (!string.IsNullOrWhiteSpace(_lateTypeString))
            {
                return $"({_lateTypeString})";
            }

            return string.Empty;
        }
    }
    /// <summary>
    /// Gets the icon representing the current field type.
    /// </summary>
    public Image Icon => FieldType.GetIcon();


    #region ISyncObject

    /// <inheritdoc/>
    void ISyncObject.Sync(IPropertySync sync, ISyncContext context)
    {
        BaseType = sync.Sync("BaseType", BaseType, SyncFlag.NotNull | SyncFlag.AffectsOthers | SyncFlag.AffectsParent) ?? new();
        IsArray = sync.Sync("IsArray", IsArray, SyncFlag.AffectsParent);

        if (sync.IsGetter())
        {
            _baseType.Optional = _optional;

            // If type resolution fails and type string exists, write type string
            if (BaseType.Id == Guid.Empty && !string.IsNullOrWhiteSpace(_lateTypeString))
            {
                sync.Sync("LateTypeString", _lateTypeString, SyncFlag.AffectsOthers | SyncFlag.AffectsParent);
            }
        }
        else if (sync.IsSetter())
        {
            // If type resolution fails, try to get type string
            if (BaseType.Id == Guid.Empty)
            {
                _lateTypeString = sync.Sync("LateTypeString", _lateTypeString, SyncFlag.AffectsOthers | SyncFlag.AffectsParent);
            }
            else
            {
                _lateTypeString = null;
            }
        }
    }

    #endregion

    #region IViewObject

    /// <inheritdoc/>
    void IViewObject.SetupView(IViewObjectSetup setup)
    {
        setup.InspectorField(BaseType, new ViewProperty("BaseType", "Base Type"));
        if (!string.IsNullOrEmpty(BaseType.SelectedKey))
        {
            if (!BaseType.GetTypeDefinition().IsDelegate)
            {
                setup.InspectorField(IsArray, new ViewProperty("IsArray", "Array"));
            }
        }
    }

    #endregion

    #region INavigable

    /// <inheritdoc/>
    object INavigable.GetNavigationTarget()
    {
        return FieldType;
    }

    #endregion

    #region ITypeDesignSelection

    /// <inheritdoc/>
    ITypeDesignSelection ITypeDesign.BaseType => _baseType;

    #endregion

    #region Resolve & Set

    /// <summary>
    /// Resolves the owner type from the owner object.
    /// </summary>
    /// <returns>The resolved <see cref="DType"/> of the owner, or null if not found.</returns>
    private DType ResolveOwnerType()
    {
        if (_owner is not IHasId hasId)
        {
            return null;
        }

        var obj = EditorObjectManager.Instance.GetObject(hasId.Id);
        if (obj is DType type)
        {
            return type;
        }

        if (obj is DField field)
        {
            return field.ParentType;
        }

        return null;
    }
    /// <summary>
    /// Resolves the late-bound type string into a <see cref="TypeDefinition"/>.
    /// </summary>
    /// <returns>The resolved type definition, or <see cref="TypeDefinition.Empty"/> if resolution fails.</returns>
    private TypeDefinition ResolveLateType()
    {
        if (string.IsNullOrWhiteSpace(_lateTypeString))
        {
            return TypeDefinition.Empty;
        }

        var type = TypeDefinition.ResolveWithTypeName(_lateTypeString);
        if (TypeDefinition.IsNullOrEmpty(type))
        {
            return TypeDefinition.Empty;
        }

        type = type.OriginType ?? TypeDefinition.Empty;
        var target = type.Target;
        if (target is null)
        {
            return TypeDefinition.Empty;
        }

        bool isLinked = false;

        var dataUsage = target.GetAttribute<DataUsageAttribute>();
        if (dataUsage != null && ((target is DStruct || target is DAbstract)))
        {
            isLinked = dataUsage.Usage.GetIsLinked();
        }

        // Handle TreeFlow special case. In TreeFlow, structure groups and referenced structures in groups must remain non-linked.
        if (dataUsage?.Usage == DataUsageMode.TreeGraph)
        {
            var myType = ResolveOwnerType();
            var myAbstract = myType as DAbstract ?? (myType as DCompond)?.BaseType;
            var targetAbstract = target as DAbstract ?? (target as DCompond)?.BaseType;

            bool sameBase = ReferenceEquals(myAbstract, targetAbstract);
            if (sameBase)
            {
                // In TreeFlow mode, when my type and target type are the same abstract type, the field relationship cannot be Linked
                isLinked = false;
            }
        }

        if (isLinked)
        {
            type = type.MakeDataLinkType();
        }

        if (_isArray)
        {
            type = type.MakeArrayType();
        }

        return type;
    }
    /// <summary>
    /// Sets the field type and updates internal state accordingly.
    /// </summary>
    /// <param name="type">The type definition to set.</param>
    private void SetFieldType(TypeDefinition type)
    {
        if (TypeDefinition.IsNullOrEmpty(type))
        {
            IsArray = false;
            _baseType.Id = Guid.Empty;
            return;
        }

        if (type.IsArray)
        {
            IsArray = true;
            _baseType.Id = type.ElementType.TargetId;
            _baseType.Prefix = TypeDefinition.GetPrefix(type.ElementType);
        }
        else
        {
            IsArray = false;
            _baseType.Id = type.TargetId;
            _baseType.Prefix = TypeDefinition.GetPrefix(type);
        }

        if (!TypeDefinition.IsNullOrEmpty(type))
        {
            // Successfully resolved type, clear string
            _lateTypeString = null;
        }
    }

    #endregion

    /// <summary>
    /// Synchronizes the default value for the current field type.
    /// </summary>
    /// <param name="value">The current value to synchronize.</param>
    /// <param name="filter">The asset filter to apply.</param>
    /// <returns>The synchronized default value, or null if not supported for this type.</returns>
    public object SyncDefaultValue(object value, IAssetFilter filter)
    {
        if (filter is null)
        {
            throw new ArgumentNullException();
        }

        var type = FieldType;
        if (type.IsStruct || type.IsArray || type.IsLink)
        {
            // Default value mode does not support: build object, array, link
            return null;
        }
        else
        {
            return type.CreateOrRepairValue(value, false);
        }
    }

    public override string ToString()
    {
        var fieldType = FieldType;
        if (TypeDefinition.IsNullOrEmpty(fieldType))
        {
            if (!string.IsNullOrWhiteSpace(_lateTypeString))
            {
                return $"Late resolve: {_lateTypeString}";
            }
            else
            {
                return string.Empty;
            }
        }

        TypeDefinition noArrayType = fieldType.IsArray ? fieldType.ElementType : fieldType;
        string str = fieldType.ToDisplayString();

        switch (noArrayType.Relationship)
        {
            case TypeRelationships.Struct:
                break;

            case TypeRelationships.DataLink:
                str += " " + L("Data Link");
                break;

            case TypeRelationships.AssetLink:
                str += " " + L("Asset Link");
                break;

            case TypeRelationships.Enum:
                str += " " + L("Enum");
                break;

            case TypeRelationships.AbstractFunction:
                break;

            case TypeRelationships.AbstractStruct:
                str += " " + L("Abstract Struct");
                break;

            case TypeRelationships.Delegate:
                str += " " + L("Delegate");
                break;

            case TypeRelationships.Array:
                break;

            default:
                break;
        }

        if (IsArray)
        {
            return str + " " + L("Array");
        }
        else
        {
            return str;
        }
    }
}