<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>Suity.Editor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Suity.DataSync\Suity.DataSync.csproj" />
    <ProjectReference Include="..\Suity.Editor\Suity.Editor.csproj" />
    <ProjectReference Include="..\Suity.Rex\Suity.Rex.csproj" />
    <ProjectReference Include="..\Suity\Suity.csproj" />
  </ItemGroup>

</Project>
