using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Suity.Editor.WinformGui")]
[assembly: InternalsVisibleTo("Suity.Editor.AvaloniaGui")]

[assembly: InternalsVisibleTo("Suity.Editor.Internal")]
[assembly: InternalsVisibleTo("Suity.Editor.Solutions")]
[assembly: InternalsVisibleTo("Suity.Editor.Test")]
[assembly: InternalsVisibleTo("Suity.Editor.ProjectView")]
[assembly: InternalsVisibleTo("Suity.Editor.ProjectGui")]
[assembly: InternalsVisibleTo("Suity.Editor.Inspector")]
[assembly: InternalsVisibleTo("Suity.Editor.VirtualTree")]
[assembly: InternalsVisibleTo("Suity.Editor.VirtualTree.Aga")]
[assembly: InternalsVisibleTo("Suity.Editor.CodeRender.Internal")]
[assembly: InternalsVisibleTo("Suity.Editor.View.Monitoring")]
[assembly: InternalsVisibleTo("Suity.Editor.GalaxyDesign")]
[assembly: InternalsVisibleTo("Suity.Editor.Clouds")]
[assembly: InternalsVisibleTo("Suity.Editor.Packaging")]
[assembly: InternalsVisibleTo("Suity.Editor.NStd")]
[assembly: InternalsVisibleTo("Suity.Editor.Compiling")]
[assembly: InternalsVisibleTo("Suity.Editor.Language.Core")]
[assembly: InternalsVisibleTo("Suity.ImGui.BuildIn")]
[assembly: InternalsVisibleTo("Suity.Editor.AIGC")]
[assembly: InternalsVisibleTo("Suity.Editor.AIGC.Flows")]
[assembly: InternalsVisibleTo("Suity.Editor.Flows")]
[assembly: InternalsVisibleTo("Suity.Editor.CodeRender")]