//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suity.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] FalseHidden {
            get {
                object obj = ResourceManager.GetObject("FalseHidden", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] inspector {
            get {
                object obj = ResourceManager.GetObject("inspector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;properties&quot;: {
        ///	&quot;@format&quot;: {
        ///	  &quot;type&quot;: &quot;string&quot;,
        ///	  &quot;enum&quot;: [&quot;SuityJson&quot;]
        ///	},
        ///	&quot;@doc&quot;: {
        ///	  &quot;type&quot;: &quot;string&quot;,
        ///	  &quot;enum&quot;: [&quot;TypeEdit&quot;]
        ///	},
        ///	&quot;NameSpace&quot;: {
        ///	  &quot;type&quot;: &quot;string&quot;,
        ///	  &quot;enum&quot;: [&quot;{{NameSpace}}&quot;]
        ///	},
        ///	&quot;Types&quot;: {
        ///	  &quot;type&quot;: &quot;array&quot;,
        ///	  &quot;items&quot;: {
        ///		&quot;type&quot;: &quot;object&quot;,
        ///		&quot;oneOf&quot;: [
        ///		  {
        ///			&quot;properties&quot;: {
        ///			  &quot;@type&quot;: {
        ///				&quot;type&quot;: &quot;string&quot;,
        ///				&quot;enum&quot;: [&quot;StructType&quot;, &quot;AbstractType&quot;],
        ///				&quot;description&quot;: &quot;StructType表示一个普通结构或、派生结构或者实现结构。若为派生结构，应该指定Base参 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SchemaTypeEdit {
            get {
                return ResourceManager.GetString("SchemaTypeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] TrueHidden {
            get {
                object obj = ResourceManager.GetObject("TrueHidden", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
