//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suity.Editor.AIGC.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suity.Editor.AIGC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;model&quot;: &quot;{AsstId}&quot;,
        ///  &quot;messages&quot;: [
        ///    {&quot;role&quot;: &quot;system&quot;, &quot;content&quot;: &quot;{System}&quot;},
        ///    {&quot;role&quot;: &quot;user&quot;, &quot;content&quot;: &quot;{User}&quot;}
        ///  ]
        ///} 的本地化字符串。
        /// </summary>
        internal static string ChatPostRequest {
            get {
                return ResourceManager.GetString("ChatPostRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;object&quot;: &quot;list&quot;,
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;msg_a1lxKwyyoul9WeCLPwHKRvNf&quot;,
        ///      &quot;object&quot;: &quot;thread.message&quot;,
        ///      &quot;created_at&quot;: 1704698202,
        ///      &quot;thread_id&quot;: &quot;thread_4IaKvSEA5EL5giDb6TTYjKaf&quot;,
        ///      &quot;role&quot;: &quot;assistant&quot;,
        ///      &quot;content&quot;: [
        ///        {
        ///          &quot;type&quot;: &quot;text&quot;,
        ///          &quot;text&quot;: {
        ///            &quot;value&quot;: &quot;是否有其他属性是您希望添加到卡牌的数据模型文档中的? 如果有任何特定的属性或细节，可以及时提供给我。&quot;,
        ///            &quot;annotations&quot;: []
        ///          }
        ///        }
        ///      ],
        ///      &quot;file_ids&quot;: [],
        ///      &quot;assistant_id&quot;: &quot;asst_N [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FakeMessage {
            get {
                return ResourceManager.GetString("FakeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Logo128 {
            get {
                object obj = ResourceManager.GetObject("Logo128", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
